name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/DetachHead/basedpyright.git
          git fetch upstream

      - name: Merge upstream/main (even if diverged)
        run: |
          git merge upstream/main --no-edit --no-ff
      - name: Push updated main to your fork
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
